services:
  postgres:
    build:
      context: .
      dockerfile: dachs/Dockerfile.dachs_postgres
      args:
        PG_VERSION: ${PG_VERSION}
        BASE_IMAGE: ${BASE_IMAGE}
        INSTALL_REPO: ${INSTALL_REPO}
        DOCKER_BIN: ${DOCKER_BIN}
    container_name: ${PG_NAME}
    tty: true
    networks:
      - dachs-net
    volumes:
      - pgdata:/var/lib/postgresql/${PG_NAME}

  dachs:
    build:
      context: .
      dockerfile: dachs/Dockerfile.dachs_server
      args:
        PG_VERSION: ${PG_VERSION}
        BASE_IMAGE: ${BASE_IMAGE}
        INSTALL_REPO: ${INSTALL_REPO}
        CONFIG_DIR: ${CONFIG_DIR}
        DOCKER_BIN: ${DOCKER_BIN}
        GAVO_DATA: ${GAVO_DATA}
    tty: true
    container_name: ${DACHS_NAME}
    ports:
      - "${SERVER_PORT}:8080"
    environment:
      - GAVO_DB_HOST=${PG_NAME}
    networks:
      - dachs-net
    volumes:
      - dachs_logs:/var/gavo

networks:
  dachs-net:
    driver: bridge

volumes:
  pgdata:
  dachs_logs:
