#!/bin/bash

echo ''
echo '=========================================================='
echo 'This image is the default option for DaCHS on Docker.'
echo 'It has the dachs & postgresql server bundled together,'
echo 'same scenario as you would have if installed the package,'
echo '`gavodachs-server`, on your own bare machine'
echo ''
echo 'That said:'
echo ' - this container exposes ports: 80 and 8080'
echo ' - Dachs` root is at:'
echo ' -- $GAVO_ROOT="/var/gavo"'
echo ' - default data location at:'
echo ' -- $GAVO_INPUTS="$GAVO_ROOT/inputs"'
echo ''
echo 'Services/daemons are *not* automatically started.'
echo 'To the suite, do (the usual):'
echo ' - service postgresql start'
echo ' - service dachs start'
echo ' - "...usual management..."'
echo ''
echo 'You should now be able to see the web interface on your'
echo 'docker host system at "http://localhost[:port-mapped]".'
echo '=========================================================='
echo ''
