ARG BASE_IMAGE="debian:stable"
ARG PG_VERSION="17"
ARG INSTALL_REPO="main"
ARG CONFIG_DIR="configs"
ARG DOCKER_BIN="bin"
ARG GAVO_DATA="data"

FROM $BASE_IMAGE

ARG PG_VERSION
ARG INSTALL_REPO
ARG CONFIG_DIR
ARG DOCKER_BIN
ARG GAVO_DATA

LABEL Description=DaCHS\ Server\ for\ compose.\ DaCHS\ is\ a\ publishing\ infrastructure\ for\ the\ Virtual\ Observatory. \
    Reference=http://arxiv.org/abs/1408.5733

# 1. Install Tools
RUN DEBIAN_FRONTEND='noninteractive' \
    && apt-get update \
    && apt-get install -y \
    curl git gnupg2 locales procps sudo vim wget \
    && apt-get clean

# 2. Setup GAVO Repo
ENV _APT_SOURCES="/etc/apt/sources.list.d/gavo.list"
COPY ${DOCKER_BIN}/apt_sources.list "$_APT_SOURCES"

RUN curl -s https://vo.ari.uni-heidelberg.de/debian/gavo-archive-keyring.asc \
    | tee /etc/apt/trusted.gpg.d/gavo-archive.keyring.asc

RUN [ "$INSTALL_REPO" != "main" ] \
    && sed -i '/deb.*backports/s/^#//' $_APT_SOURCES \
    || echo "Using main repo"

# 3. Environment and DaCHS Vars
ENV LC_ALL=C.UTF-8
ENV GAVO_ROOT="/var/gavo"
ENV GAVO_INPUTS="${GAVO_ROOT}/inputs"
ENV GAVO_SETTINGS="/etc/gavo.rc"
ENV GAVOSETTINGS="$GAVO_SETTINGS"
ENV PG_VERSION=${PG_VERSION}

# 4. Install DaCHS and Client-side Extensions
RUN DEBIAN_FRONTEND='noninteractive' && \
    apt-get update && \
    apt-get install -y python3-gavo postgresql-$PG_VERSION-q3c && \
    apt-get clean

# 5. User Permissions
RUN addgroup --system gavo && \
    adduser --system --ingroup gavo gavo && \
    adduser --disabled-password --gecos "" --ingroup gavo dachsroot && \
    adduser --quiet gavo gavo && \
    adduser --quiet dachsroot gavo && \
    mkdir -p -m 775 "${GAVO_ROOT}" && \
    chown dachsroot "${GAVO_ROOT}"

# 6. Config and Launch
COPY ${DOCKER_BIN}/gavo.rc "$GAVO_SETTINGS"
COPY ${CONFIG_DIR}/gavo.r[c] "$GAVO_SETTINGS"
COPY ${CONFIG_DIR}/defaultmeta.tx[t] ${GAVO_ROOT}/etc/
COPY ${CONFIG_DIR}/userconfig.r[d] ${GAVO_ROOT}/etc/

# Adding a directory to store data locally
RUN mkdir ${GAVO_DATA}

ENV GAVO_PORT=8080
EXPOSE $GAVO_PORT

COPY ${DOCKER_BIN}/dachs_server.sh /serve.sh
ENTRYPOINT ["/bin/bash"]
CMD ["--rcfile", "/serve.sh"]